package quadlets

import "github.com/lugoues/creidhne@v0"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

web: creidhne.#Quadlet & {
	name: "web"
	units: {
		#network: {}
		#container: {
			Container: {
				Image: "docker.io/library/nginx:1.27"
				Exec:  "nginx -g \"daemon off;\""
				Environment: [
					"NGINX_HOST=example.com",
				]
				Network: [
					units.#network.#self,
				]
				PublishPort: [
					"8080:80",
				]
				Volume: [
					"./site:/usr/share/nginx/html:ro",
				]
				Label: [
					"app=web",
				]
			}
			Service: {
				Restart: "always"
			}
		}
	}
}

// ─── source: testdata/single-basic/compose.yaml ───
// name: web
// services:
//   nginx:
//     image: docker.io/library/nginx:1.27
//     command: ["nginx", "-g", "daemon off;"]
//     ports:
//       - "8080:80"
//     environment:
//       NGINX_HOST: example.com
//     volumes:
//       - ./site:/usr/share/nginx/html:ro
//     labels:
//       app: web
//     restart: always
