package quadlets

import "github.com/lugoues/creidhne@v0"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

netty: creidhne.#Quadlet & {
	name: "netty"
	units: {
		networks: {
			appnet: {
				Network: {
					Internal: true
					IPv6:     true
					Subnet: [
						"10.89.0.0/24",
					]
					Gateway: [
						"10.89.0.1",
					]
					IPRange: [
						"10.89.0.128/25",
					]
					Options: [
						"mtu=9000",
					]
				}
			}
			ext: {
				Network: {
					NetworkName: "prod-net"
				}
			}
		}
		#volume: {
			Volume: {
				VolumeName: "prod-data"
			}
		}
		#container: {
			Container: {
				Image: "docker.io/library/nginx:1.27"
				Network: [
					units.networks.appnet.#self & {alias: ["web", "www"], ip: "10.89.0.5"},
					units.networks.ext.#self,
				]
				Volume: [
					units.#volume.#self & {target: "/data"},
				]
			}
		}
	}
}

// ─── source: testdata/external-ipam/compose.yaml ───
// name: netty
// services:
//   app:
//     image: docker.io/library/nginx:1.27
//     networks:
//       appnet:
//         aliases: [web, www]
//         ipv4_address: 10.89.0.5
//       ext: {}
//     volumes:
//       - extvol:/data
// networks:
//   appnet:
//     driver: bridge
//     internal: true
//     enable_ipv6: true
//     driver_opts: {mtu: "9000"}
//     ipam:
//       config:
//         - subnet: 10.89.0.0/24
//           gateway: 10.89.0.1
//           ip_range: 10.89.0.128/25
//   ext:
//     external: true
//     name: prod-net
// volumes:
//   extvol:
//     external: true
//     name: prod-data
