package quadlets

import "github.com/lugoues/creidhne@v0"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

swarmy: creidhne.#Quadlet & {
	name: "swarmy"
	units: {
		networks: {
			default: {}
		}
		containers: {
			app: {
				// compose links: [db] (not mapped; see conversion report)
				// compose pid: host (not mapped; see conversion report)
				// compose ipc: host (not mapped; see conversion report)
				// compose cgroup_parent: legacy.slice (not mapped; see conversion report)
				// compose platform: linux/amd64 (not mapped; see conversion report)
				// compose oom_score_adj: 100 (not mapped; see conversion report)
				// compose domainname: corp.example (not mapped; see conversion report)
				// compose oom_kill_disable: true (not mapped; see conversion report)
				// compose pre_start/post_start/pre_stop: 1 hook(s) (not mapped; see conversion report)
				// compose scale: 3 (not mapped; see conversion report)
				// compose stdin_open: true (not mapped; see conversion report)
				// compose tty: true (not mapped; see conversion report)
				// compose volumes_from: [db] (not mapped; see conversion report)
				Container: {
					Image: "docker.io/library/nginx:1.27"
					Network: [
						units.networks.default.#self,
					]
				}
				Unit: {
					After: [
						units.containers.db.#service,
					]
					Requires: [
						units.containers.db.#service,
					]
				}
			}
			db: {
				Container: {
					Image: "docker.io/library/postgres:16"
					Network: [
						units.networks.default.#self & {mac: "02:42:ac:11:00:02"},
					]
				}
			}
		}
	}
}

// ─── source: testdata/unsupported/compose.yaml ───
// name: swarmy
// services:
//   app:
//     image: docker.io/library/nginx:1.27
//     links: [db]
//     pid: host
//     ipc: host
//     platform: linux/amd64
//     cgroup_parent: legacy.slice
//     oom_score_adj: 100
//     oom_kill_disable: true
//     stdin_open: true
//     tty: true
//     domainname: corp.example
//     volumes_from: [db]
//     scale: 3
//     post_start:
//       - command: ["/bin/setup.sh"]
//     deploy:
//       mode: global
//       replicas: 3
//       endpoint_mode: vip
//       labels: {swarm.only: "true"}
//       placement:
//         constraints: ["node.role == manager"]
//       update_config: {parallelism: 2}
//       restart_policy: {condition: on-failure}
//   db:
//     image: docker.io/library/postgres:16
//     mac_address: "02:42:ac:11:00:02"
// configs:
//   app_config:
//     file: ./config.json
