package cli

import (
	"strings"
	"testing"
)

// A project whose registry declares app-db (explicit name) and api_key (name
// defaults to the key).
const secretsRegistryMain = `package config

import q "github.com/lugoues/creidhne@v0"

secrets: q.#SecretRegistry & {
	app_db:  {name: "app-db"}
	api_key: _
}
`

// stubSecrets swaps the podman/valuer hooks for the duration of a test (podman
// isn't available, and the huh form needs a TTY).
func stubSecrets(t *testing.T, existing map[string]bool, create func(string, []byte, bool) error, value func(string) ([]byte, bool, error)) {
	t.Helper()
	ol, oc, ov := podmanListSecrets, podmanCreateSecret, secretValuer
	t.Cleanup(func() { podmanListSecrets, podmanCreateSecret, secretValuer = ol, oc, ov })
	podmanListSecrets = func() (map[string]bool, error) { return existing, nil }
	podmanCreateSecret = create
	secretValuer = value
}

// TestCmdSecretsList drives `crei secrets` end to end (registry extraction + the
// podman existence check, with podman stubbed). app-db exists, api_key does not,
// exercising both the name-override and default-name registry forms.
func TestCmdSecretsList(t *testing.T) {
	dir := setupProject(t, secretsRegistryMain)
	stubSecrets(t, map[string]bool{"app-db": true}, nil, nil)

	out, err := runCmd(t, "--dir", dir, "secrets")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"app-db", "present", "api_key", "missing", "1 present, 1 missing"} {
		if !strings.Contains(out, want) {
			t.Errorf("secrets output missing %q:\n%s", want, out)
		}
	}
}

// TestCmdSecretsNoRegistry: with no registry, the command reports that and never
// shells out to podman.
func TestCmdSecretsNoRegistry(t *testing.T) {
	dir := setupProject(t, testMain) // a quadlet, no `secrets` registry
	called := false
	stubSecrets(t, nil, nil, nil)
	podmanListSecrets = func() (map[string]bool, error) { called = true; return nil, nil }

	out, err := runCmd(t, "--dir", dir, "secrets")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "No secrets declared") {
		t.Errorf("want 'No secrets declared', got:\n%s", out)
	}
	if called {
		t.Error("podman must not be queried when there is no registry")
	}
}

// TestCmdSecretsCreateAll: -a creates every registry secret missing from podman.
func TestCmdSecretsCreateAll(t *testing.T) {
	dir := setupProject(t, secretsRegistryMain)
	created := map[string]string{}
	stubSecrets(t, map[string]bool{}, // none exist yet
		func(name string, v []byte, _ bool) error { created[name] = string(v); return nil },
		func(name string) ([]byte, bool, error) { return []byte("v-" + name), false, nil },
	)

	out, err := runCmd(t, "--dir", dir, "secrets", "create", "-a")
	if err != nil {
		t.Fatal(err)
	}
	if created["app-db"] != "v-app-db" || created["api_key"] != "v-api_key" {
		t.Fatalf("expected both secrets created, got %v", created)
	}
	if !strings.Contains(out, "created") {
		t.Errorf("want a 'created' line:\n%s", out)
	}
}

// TestCmdSecretsCreateSkipsExisting: creating an existing secret without
// --replace skips it and never calls create.
func TestCmdSecretsCreateSkipsExisting(t *testing.T) {
	dir := setupProject(t, secretsRegistryMain)
	created := map[string]string{}
	stubSecrets(t, map[string]bool{"app-db": true},
		func(name string, v []byte, _ bool) error { created[name] = string(v); return nil },
		func(string) ([]byte, bool, error) { return []byte("x"), false, nil },
	)

	out, err := runCmd(t, "--dir", dir, "secrets", "create", "app-db")
	if err != nil {
		t.Fatal(err)
	}
	if len(created) != 0 {
		t.Fatalf("existing secret should be skipped, created %v", created)
	}
	if !strings.Contains(out, "already exists") {
		t.Errorf("want a skip notice:\n%s", out)
	}
}

// TestCmdSecretsCreateArgs: exactly one of a name or -a is required.
func TestCmdSecretsCreateArgs(t *testing.T) {
	dir := setupProject(t, secretsRegistryMain)
	stubSecrets(t, map[string]bool{},
		func(string, []byte, bool) error { return nil },
		func(string) ([]byte, bool, error) { return nil, false, nil },
	)
	if _, err := runCmd(t, "--dir", dir, "secrets", "create"); err == nil {
		t.Error("create with neither a name nor -a should error")
	}
	if _, err := runCmd(t, "--dir", dir, "secrets", "create", "-a", "app-db"); err == nil {
		t.Error("create with both a name and -a should error")
	}
}

func TestGeneratePassword(t *testing.T) {
	a, err := generatePassword(32)
	if err != nil {
		t.Fatal(err)
	}
	if len(a) != 32 {
		t.Fatalf("length %d, want 32", len(a))
	}
	for _, c := range a {
		if !strings.ContainsRune(passwordCharset, rune(c)) {
			t.Fatalf("generated byte %q not in charset", c)
		}
	}
	if b, _ := generatePassword(32); string(a) == string(b) {
		t.Error("two generations should differ")
	}
	if d, _ := generatePassword(0); len(d) != 32 {
		t.Errorf("n<=0 should default to 32, got %d", len(d))
	}
}
