package quadlets

import "github.com/lugoues/creidhne"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

crawler: creidhne.#Quadlet & {
	name: "crawler"
	units: {
		networks: {
			default: {}
		}
		containers: {
			api: {
				Container: {
					Image: "ghcr.io/acme/crawler-api:latest"
					Exec:  "node dist/src/harness.js --start-docker"
					Environment: [
						"API_KEY=",
						"BUS_URL=amqp://rabbitmq:5672",
						"HOST=0.0.0.0",
						"LOGGING_LEVEL=info",
						"PORT=3002",
					]
					Network: [
						units.networks.default.#self,
					]
					PublishPort: [
						"3002:3002",
					]
				}
				Service: {
					MemoryMax: "8589934592"
					CPUQuota:  "400%"
				}
				Unit: {
					After: [
						units.containers.rabbitmq.#service,
					]
					Requires: [
						units.containers.rabbitmq.#service,
					]
				}
			}
			init: {
				Container: {
					Image:      "docker.io/library/bash:5"
					Entrypoint: "[\"/bin/bash\",\"-c\",\"out=$(probe 2>&1); status=$?; printf '%s' \\\"$out\\\"; exit $status\"]"
					Network: [
						units.networks.default.#self,
					]
				}
				Unit: {
					After: [
						units.containers.api.#service,
					]
					Requires: [
						units.containers.api.#service,
					]
				}
			}
			rabbitmq: {
				Container: {
					Image: "docker.io/library/rabbitmq:3"
					Network: [
						units.networks.default.#self,
					]
					HealthCmd:      "rabbitmq-diagnostics ping"
					HealthInterval: "10s"
					Notify:         "healthy"
				}
				Service: {
					Type:         "notify"
					NotifyAccess: "all"
				}
			}
		}
	}
}

// ─── source: testdata/resolve-structured/compose.yaml ───
// name: crawler
// x-common: &common-env
//   LOGGING_LEVEL: ${LOGGING_LEVEL:-info}
// services:
//   api:
//     image: ghcr.io/acme/crawler-api:latest
//     environment:
//       <<: *common-env
//       HOST: "0.0.0.0"
//       PORT: ${INTERNAL_PORT:-3002}
//       BUS_URL: amqp://rabbitmq:5672
//       API_KEY: ${API_KEY}
//     ports:
//       - "${PORT:-3002}:${INTERNAL_PORT:-3002}"
//     depends_on:
//       rabbitmq:
//         condition: service_healthy
//     command: node dist/src/harness.js --start-docker
//     cpus: 4.0
//     mem_limit: 8G
//   rabbitmq:
//     image: docker.io/library/rabbitmq:3
//     healthcheck:
//       test: ["CMD", "rabbitmq-diagnostics", "ping"]
//       interval: 10s
//   init:
//     image: docker.io/library/bash:5
//     entrypoint:
//       - /bin/bash
//       - -c
//       - "out=$(probe 2>&1); status=$$?; printf '%s' \"$$out\"; exit $$status"
//     depends_on: [api]
