package quadlets

import "github.com/lugoues/creidhne@v0"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

// Compose ${VAR} references, lifted so unresolved configuration fails
// validate loudly. Fill these in (or re-import with --env-file).
env: {
	APP_VERSION: string | *"latest"
	DB_PASSWORD: string
	APP_HOME:    string
	PASSTHRU:    string
}

envy: creidhne.#Quadlet & {
	name: "envy"
	units: {
		#network: {}
		#container: {
			Container: {
				Image: "ghcr.io/acme/app:\(env.APP_VERSION)"
				Environment: [
					"DB_PASSWORD=\(env.DB_PASSWORD)",
					"HOME_REF=\(env.APP_HOME)",
					"LITERAL_DOLLAR=cost$5",
					"PASSTHRU=\(env.PASSTHRU)",
				]
				Network: [
					units.#network.#self,
				]
				Label: [
					"note=pinned \(env.APP_VERSION)",
				]
			}
		}
	}
}

// ─── source: testdata/env-vars/compose.yaml ───
// name: envy
// services:
//   app:
//     image: "ghcr.io/acme/app:${APP_VERSION:-latest}"
//     environment:
//       DB_PASSWORD: ${DB_PASSWORD}
//       LITERAL_DOLLAR: "cost$$5"
//       HOME_REF: $APP_HOME
//       PASSTHRU:
//     labels:
//       note: "pinned ${APP_VERSION:-latest}"
