package quadlets

import "github.com/lugoues/creidhne"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

// Compose ${VAR} references, lifted so unresolved configuration fails
// validate loudly. Fill these in (or re-import with --env-file).
env: {
	TAG: string
}

collide: creidhne.#Quadlet & {
	name: "collide"
	units: {
		networks: {
			default: {}
		}
		containers: {
			foo_bar: {
				name: "foo-bar"
				Container: {
					Image: "docker.io/library/alpine:latest"
					Network: [
						units.networks.default.#self,
					]
				}
			}
			foo_bar_2: {
				name: "foo_bar"
				Container: {
					Image: "docker.io/library/alpine:latest"
					Network: [
						units.networks.default.#self,
					]
				}
			}
			web: {
				Container: {
					Image: "docker.io/library/nginx:\(env.TAG)"
					Network: [
						units.networks.default.#self,
					]
					PublishPort: [
						"[::1]:8080:80",
					]
				}
			}
		}
	}
}

// ─── source: testdata/collide-ipv6-nested/compose.yaml ───
// name: collide
// services:
//   foo-bar:
//     image: docker.io/library/alpine:latest
//   foo_bar:
//     image: docker.io/library/alpine:latest
//   web:
//     image: docker.io/library/nginx:${TAG:-${FALLBACK:-latest}}
//     ports:
//       - target: 80
//         published: "8080"
//         host_ip: "::1"
