package quadlets

import "github.com/lugoues/creidhne"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

// Podman secrets referenced by the containers. Values are never
// imported: load them per the conversion report (crei secrets list
// shows what is still missing).
secrets: creidhne.#SecretRegistry & {
	db_password: {name: "forge_db_password"}
	npm_token: {name: "forge_npm_token"}
	tls_cert: {name: "prod-tls-cert"}
}

forge: creidhne.#Quadlet & {
	name: "forge"
	units: {
		networks: {
			buildnet: {}
			default: {}
		}
		builds: {
			app: {
				Build: {
					SetWorkingDirectory: "./app"
					File:                "Build.Dockerfile"
					ImageTag: [
						"localhost/forge-app:latest",
						"localhost/forge-app:edge",
					]
					Target: "prod"
					Network: [
						units.networks.buildnet.#self,
					]
					Secret: [
						"id=npm_token,src=./npm_token.txt",
					]
					BuildArg: [
						"VERSION=3",
					]
				}
			}
		}
		containers: {
			app: {
				Container: {
					Image: units.builds.app.#self
					Network: [
						units.networks.default.#self,
					]
					Secret: [
						secrets.db_password,
						secrets.tls_cert & {target: "/etc/ssl/app.pem", mode: "0400"},
					]
				}
			}
			db: {
				Container: {
					Image: "docker.io/library/postgres:16"
					Network: [
						units.networks.default.#self,
					]
					Secret: [
						secrets.db_password,
					]
				}
			}
		}
	}
}

// ─── source: testdata/build-secrets/compose.yaml ───
// name: forge
// services:
//   app:
//     build:
//       context: ./app
//       dockerfile: Build.Dockerfile
//       args:
//         VERSION: "3"
//       target: prod
//       tags: ["localhost/forge-app:edge"]
//       network: buildnet
//       secrets: [npm_token]
//     image: localhost/forge-app:latest
//     secrets:
//       - db_password
//       - source: tls_cert
//         target: /etc/ssl/app.pem
//         mode: 0400
//   db:
//     image: docker.io/library/postgres:16
//     secrets: [db_password]
// networks:
//   buildnet: {}
// secrets:
//   db_password:
//     file: ./db_password.txt
//   tls_cert:
//     external: true
//     name: prod-tls-cert
//   npm_token:
//     file: ./npm_token.txt
