{{- /* Code generated by tools/gen-systemd-sections from systemd v257; DO NOT EDIT. */ -}}
{{- define "unit" -}}
{{ if . -}}
[Unit]
{{ if isset . "Description" -}}Description={{ .Description }}
{{ end -}}
{{ range .Documentation -}}Documentation={{ . }}
{{ end -}}
{{ if isset . "SourcePath" -}}SourcePath={{ .SourcePath }}
{{ end -}}
{{ range .Requires -}}Requires={{ . }}
{{ end -}}
{{ range .Requisite -}}Requisite={{ . }}
{{ end -}}
{{ range .Wants -}}Wants={{ . }}
{{ end -}}
{{ range .BindsTo -}}BindsTo={{ . }}
{{ end -}}
{{ range .Upholds -}}Upholds={{ . }}
{{ end -}}
{{ range .Conflicts -}}Conflicts={{ . }}
{{ end -}}
{{ range .Before -}}Before={{ . }}
{{ end -}}
{{ range .After -}}After={{ . }}
{{ end -}}
{{ range .OnSuccess -}}OnSuccess={{ . }}
{{ end -}}
{{ range .OnFailure -}}OnFailure={{ . }}
{{ end -}}
{{ range .PropagatesReloadTo -}}PropagatesReloadTo={{ . }}
{{ end -}}
{{ range .ReloadPropagatedFrom -}}ReloadPropagatedFrom={{ . }}
{{ end -}}
{{ range .PropagatesStopTo -}}PropagatesStopTo={{ . }}
{{ end -}}
{{ range .StopPropagatedFrom -}}StopPropagatedFrom={{ . }}
{{ end -}}
{{ range .PartOf -}}PartOf={{ . }}
{{ end -}}
{{ range .JoinsNamespaceOf -}}JoinsNamespaceOf={{ . }}
{{ end -}}
{{ range .RequiresMountsFor -}}RequiresMountsFor={{ . }}
{{ end -}}
{{ range .WantsMountsFor -}}WantsMountsFor={{ . }}
{{ end -}}
{{ if isset . "StopWhenUnneeded" -}}StopWhenUnneeded={{ .StopWhenUnneeded }}
{{ end -}}
{{ if isset . "RefuseManualStart" -}}RefuseManualStart={{ .RefuseManualStart }}
{{ end -}}
{{ if isset . "RefuseManualStop" -}}RefuseManualStop={{ .RefuseManualStop }}
{{ end -}}
{{ if isset . "AllowIsolate" -}}AllowIsolate={{ .AllowIsolate }}
{{ end -}}
{{ if isset . "DefaultDependencies" -}}DefaultDependencies={{ .DefaultDependencies }}
{{ end -}}
{{ if isset . "SurviveFinalKillSignal" -}}SurviveFinalKillSignal={{ .SurviveFinalKillSignal }}
{{ end -}}
{{ if isset . "OnSuccessJobMode" -}}OnSuccessJobMode={{ .OnSuccessJobMode }}
{{ end -}}
{{ if isset . "OnFailureJobMode" -}}OnFailureJobMode={{ .OnFailureJobMode }}
{{ end -}}
{{ if isset . "OnFailureIsolate" -}}OnFailureIsolate={{ .OnFailureIsolate }}
{{ end -}}
{{ if isset . "IgnoreOnIsolate" -}}IgnoreOnIsolate={{ .IgnoreOnIsolate }}
{{ end -}}
{{ if isset . "JobTimeoutSec" -}}JobTimeoutSec={{ .JobTimeoutSec }}
{{ end -}}
{{ if isset . "JobRunningTimeoutSec" -}}JobRunningTimeoutSec={{ .JobRunningTimeoutSec }}
{{ end -}}
{{ if isset . "JobTimeoutAction" -}}JobTimeoutAction={{ .JobTimeoutAction }}
{{ end -}}
{{ if isset . "JobTimeoutRebootArgument" -}}JobTimeoutRebootArgument={{ .JobTimeoutRebootArgument }}
{{ end -}}
{{ if isset . "StartLimitIntervalSec" -}}StartLimitIntervalSec={{ .StartLimitIntervalSec }}
{{ end -}}
{{ if isset . "StartLimitBurst" -}}StartLimitBurst={{ printf "%d" .StartLimitBurst }}
{{ end -}}
{{ if isset . "StartLimitAction" -}}StartLimitAction={{ .StartLimitAction }}
{{ end -}}
{{ if isset . "FailureAction" -}}FailureAction={{ .FailureAction }}
{{ end -}}
{{ if isset . "SuccessAction" -}}SuccessAction={{ .SuccessAction }}
{{ end -}}
{{ if isset . "FailureActionExitStatus" -}}FailureActionExitStatus={{ .FailureActionExitStatus }}
{{ end -}}
{{ if isset . "SuccessActionExitStatus" -}}SuccessActionExitStatus={{ .SuccessActionExitStatus }}
{{ end -}}
{{ if isset . "RebootArgument" -}}RebootArgument={{ .RebootArgument }}
{{ end -}}
{{ range .ConditionPathExists -}}ConditionPathExists={{ . }}
{{ end -}}
{{ range .ConditionPathExistsGlob -}}ConditionPathExistsGlob={{ . }}
{{ end -}}
{{ range .ConditionPathIsDirectory -}}ConditionPathIsDirectory={{ . }}
{{ end -}}
{{ range .ConditionPathIsSymbolicLink -}}ConditionPathIsSymbolicLink={{ . }}
{{ end -}}
{{ range .ConditionPathIsMountPoint -}}ConditionPathIsMountPoint={{ . }}
{{ end -}}
{{ range .ConditionPathIsReadWrite -}}ConditionPathIsReadWrite={{ . }}
{{ end -}}
{{ range .ConditionPathIsEncrypted -}}ConditionPathIsEncrypted={{ . }}
{{ end -}}
{{ range .ConditionDirectoryNotEmpty -}}ConditionDirectoryNotEmpty={{ . }}
{{ end -}}
{{ range .ConditionFileNotEmpty -}}ConditionFileNotEmpty={{ . }}
{{ end -}}
{{ range .ConditionFileIsExecutable -}}ConditionFileIsExecutable={{ . }}
{{ end -}}
{{ range .ConditionNeedsUpdate -}}ConditionNeedsUpdate={{ . }}
{{ end -}}
{{ range .ConditionFirstBoot -}}ConditionFirstBoot={{ . }}
{{ end -}}
{{ range .ConditionArchitecture -}}ConditionArchitecture={{ . }}
{{ end -}}
{{ range .ConditionFirmware -}}ConditionFirmware={{ . }}
{{ end -}}
{{ range .ConditionVirtualization -}}ConditionVirtualization={{ . }}
{{ end -}}
{{ range .ConditionHost -}}ConditionHost={{ . }}
{{ end -}}
{{ range .ConditionKernelCommandLine -}}ConditionKernelCommandLine={{ . }}
{{ end -}}
{{ range .ConditionKernelVersion -}}ConditionKernelVersion={{ . }}
{{ end -}}
{{ range .ConditionCredential -}}ConditionCredential={{ . }}
{{ end -}}
{{ range .ConditionSecurity -}}ConditionSecurity={{ . }}
{{ end -}}
{{ range .ConditionCapability -}}ConditionCapability={{ . }}
{{ end -}}
{{ range .ConditionACPower -}}ConditionACPower={{ . }}
{{ end -}}
{{ range .ConditionMemory -}}ConditionMemory={{ . }}
{{ end -}}
{{ range .ConditionCPUFeature -}}ConditionCPUFeature={{ . }}
{{ end -}}
{{ range .ConditionCPUs -}}ConditionCPUs={{ . }}
{{ end -}}
{{ range .ConditionEnvironment -}}ConditionEnvironment={{ . }}
{{ end -}}
{{ range .ConditionUser -}}ConditionUser={{ . }}
{{ end -}}
{{ range .ConditionGroup -}}ConditionGroup={{ . }}
{{ end -}}
{{ range .ConditionControlGroupController -}}ConditionControlGroupController={{ . }}
{{ end -}}
{{ range .ConditionOSRelease -}}ConditionOSRelease={{ . }}
{{ end -}}
{{ range .ConditionMemoryPressure -}}ConditionMemoryPressure={{ . }}
{{ end -}}
{{ range .ConditionCPUPressure -}}ConditionCPUPressure={{ . }}
{{ end -}}
{{ range .ConditionIOPressure -}}ConditionIOPressure={{ . }}
{{ end -}}
{{ range .AssertPathExists -}}AssertPathExists={{ . }}
{{ end -}}
{{ range .AssertPathExistsGlob -}}AssertPathExistsGlob={{ . }}
{{ end -}}
{{ range .AssertPathIsDirectory -}}AssertPathIsDirectory={{ . }}
{{ end -}}
{{ range .AssertPathIsSymbolicLink -}}AssertPathIsSymbolicLink={{ . }}
{{ end -}}
{{ range .AssertPathIsMountPoint -}}AssertPathIsMountPoint={{ . }}
{{ end -}}
{{ range .AssertPathIsReadWrite -}}AssertPathIsReadWrite={{ . }}
{{ end -}}
{{ range .AssertPathIsEncrypted -}}AssertPathIsEncrypted={{ . }}
{{ end -}}
{{ range .AssertDirectoryNotEmpty -}}AssertDirectoryNotEmpty={{ . }}
{{ end -}}
{{ range .AssertFileNotEmpty -}}AssertFileNotEmpty={{ . }}
{{ end -}}
{{ range .AssertFileIsExecutable -}}AssertFileIsExecutable={{ . }}
{{ end -}}
{{ range .AssertNeedsUpdate -}}AssertNeedsUpdate={{ . }}
{{ end -}}
{{ range .AssertFirstBoot -}}AssertFirstBoot={{ . }}
{{ end -}}
{{ range .AssertArchitecture -}}AssertArchitecture={{ . }}
{{ end -}}
{{ range .AssertVirtualization -}}AssertVirtualization={{ . }}
{{ end -}}
{{ range .AssertHost -}}AssertHost={{ . }}
{{ end -}}
{{ range .AssertKernelCommandLine -}}AssertKernelCommandLine={{ . }}
{{ end -}}
{{ range .AssertKernelVersion -}}AssertKernelVersion={{ . }}
{{ end -}}
{{ range .AssertCredential -}}AssertCredential={{ . }}
{{ end -}}
{{ range .AssertSecurity -}}AssertSecurity={{ . }}
{{ end -}}
{{ range .AssertCapability -}}AssertCapability={{ . }}
{{ end -}}
{{ range .AssertACPower -}}AssertACPower={{ . }}
{{ end -}}
{{ range .AssertMemory -}}AssertMemory={{ . }}
{{ end -}}
{{ range .AssertCPUFeature -}}AssertCPUFeature={{ . }}
{{ end -}}
{{ range .AssertCPUs -}}AssertCPUs={{ . }}
{{ end -}}
{{ range .AssertEnvironment -}}AssertEnvironment={{ . }}
{{ end -}}
{{ range .AssertUser -}}AssertUser={{ . }}
{{ end -}}
{{ range .AssertGroup -}}AssertGroup={{ . }}
{{ end -}}
{{ range .AssertControlGroupController -}}AssertControlGroupController={{ . }}
{{ end -}}
{{ range .AssertOSRelease -}}AssertOSRelease={{ . }}
{{ end -}}
{{ range .AssertMemoryPressure -}}AssertMemoryPressure={{ . }}
{{ end -}}
{{ range .AssertCPUPressure -}}AssertCPUPressure={{ . }}
{{ end -}}
{{ range .AssertIOPressure -}}AssertIOPressure={{ . }}
{{ end -}}
{{ if isset . "CollectMode" -}}CollectMode={{ .CollectMode }}
{{ end -}}
{{ end -}}
{{- end -}}
{{- define "install" -}}
{{ if . }}
[Install]
{{ range .Alias -}}Alias={{ . }}
{{ end -}}
{{ range .WantedBy -}}WantedBy={{ . }}
{{ end -}}
{{ range .RequiredBy -}}RequiredBy={{ . }}
{{ end -}}
{{ range .UpheldBy -}}UpheldBy={{ . }}
{{ end -}}
{{ range .Also -}}Also={{ . }}
{{ end -}}
{{ if isset . "DefaultInstance" -}}DefaultInstance={{ .DefaultInstance }}
{{ end -}}
{{ end -}}
{{- end -}}
