package importer

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"cuelang.org/go/cue/format"
)

// emit renders the model as a formatted CUE file. The text is generated
// naively (indentation via cue/format afterwards) and then parsed/formatted
// by format.Source, which both canonicalizes layout and rejects anything
// syntactically invalid.
func emit(m *model) ([]byte, error) {
	var b bytes.Buffer
	w := func(f string, args ...any) { fmt.Fprintf(&b, f+"\n", args...) }

	w("package %s", m.pkg)
	w("")
	w("import \"github.com/lugoues/creidhne@v0\"")
	w("")
	w("// Generated by crei import compose. This file is yours now: review the")
	w("// conversion report, then crei validate && crei plan.")

	if len(m.env.order) > 0 {
		w("")
		w("// Compose ${VAR} references, lifted so unresolved configuration fails")
		w("// validate loudly. Fill these in (or re-import with --env-file).")
		w("env: {")
		for _, f := range m.env.fields() {
			w("%s: %s", cueKey(f.k), f.v)
		}
		w("}")
	}

	if len(m.secrets) > 0 {
		w("")
		w("// Podman secrets referenced by the containers. Values are never")
		w("// imported: load them per the conversion report (crei secrets list")
		w("// shows what is still missing).")
		w("secrets: creidhne.#SecretRegistry & {")
		for _, s := range m.secrets {
			if s.name != "" {
				w("%s: {name: %s}", cueKey(s.key), strconv.Quote(s.name))
			} else {
				w("%s: _", cueKey(s.key))
			}
		}
		w("}")
	}

	w("")
	// The top-level field gets an identifier key; the name: field (which
	// drives stems/filenames) keeps the original spelling.
	quadletKey := m.quadletName
	if !identRe.MatchString(quadletKey) {
		if cand := strings.NewReplacer("-", "_", ".", "_").Replace(quadletKey); identRe.MatchString(cand) {
			quadletKey = cand
		}
	}
	w("%s: creidhne.#Quadlet & {", cueKey(quadletKey))
	w("name: %s", strconv.Quote(m.quadletName))
	w("units: {")

	emitKind(w, "networks", "#network", m.networks, m.forms.singularNetwork)
	emitKind(w, "volumes", "#volume", m.volumes, m.forms.singularVolume)
	emitKind(w, "builds", "#build", m.builds, m.forms.singularBuild)
	emitKind(w, "containers", "#container", m.containers, m.forms.singularContainer)

	w("}")
	w("}")

	for _, s := range m.sources {
		w("")
		w("// ─── source: %s ───", s.label)
		for _, line := range strings.Split(strings.TrimRight(s.content, "\n"), "\n") {
			if line == "" {
				w("//")
				continue
			}
			w("// %s", line)
		}
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("internal: emitted CUE does not parse: %w\n%s", err, b.Bytes())
	}
	return out, nil
}

// emitKind writes one unit kind, as the singular metafield form when the
// project reduces to a single service (and a single unit of the kind), else
// the plural map form keyed by compose names.
func emitKind(w func(string, ...any), plural, singular string, units []unitDef, useSingular bool) {
	if len(units) == 0 {
		return
	}
	if useSingular {
		emitUnitBody(w, singular+":", units[0])
		return
	}
	w("%s: {", plural)
	for _, u := range units {
		emitUnitBody(w, cueKey(u.key)+":", u)
	}
	w("}")
}

func emitUnitBody(w func(string, ...any), label string, u unitDef) {
	for _, c := range u.comments {
		w("// %s", c)
	}
	empty := true
	for _, s := range u.sections {
		if len(s.fields) > 0 {
			empty = false
		}
	}
	if empty && u.name == "" && len(u.bodyComments) == 0 {
		w("%s {}", label)
		return
	}
	w("%s {", label)
	for _, c := range u.bodyComments {
		w("// %s", c)
	}
	if u.name != "" {
		w("name: %s", strconv.Quote(u.name))
	}
	for _, s := range u.sections {
		if len(s.fields) == 0 {
			continue
		}
		if s.name == "" {
			emitFields(w, s.fields)
			continue
		}
		w("%s: {", s.name)
		emitFields(w, s.fields)
		w("}")
	}
	w("}")
}

// emitFields writes scalar fields inline and list fields one element per
// line, so diffs stay reviewable even for single-element lists.
func emitFields(w func(string, ...any), fields []kv) {
	for _, f := range fields {
		if f.items == nil {
			w("%s: %s", cueKey(f.k), f.v)
			continue
		}
		w("%s: [", cueKey(f.k))
		for _, it := range f.items {
			w("%s,", it)
		}
		w("]")
	}
}
