package quadlets

import "github.com/lugoues/creidhne"

// Generated by crei import compose. This file is yours now: review the
// conversion report, then crei validate && crei plan.

paperless: creidhne.#Quadlet & {
	name: "paperless"
	units: {
		networks: {
			default: {}
		}
		volumes: {
			data: {}
			pg_data: {
				name: "pg-data"
			}
		}
		containers: {
			db: {
				Container: {
					Image: "docker.io/library/postgres:16"
					Network: [
						units.networks.default.#self,
					]
					Volume: [
						units.volumes.pg_data.#self & {target: "/var/lib/postgresql/data"},
					]
					HealthCmd:      "pg_isready -U paperless"
					HealthInterval: "30s"
					HealthTimeout:  "5s"
					HealthRetries:  5
					Notify:         "healthy"
				}
				Service: {
					Restart:         "always"
					Type:            "notify"
					NotifyAccess:    "all"
					TimeoutStartSec: "185s"
				}
			}
			redis_broker: {
				name: "redis-broker"
				Container: {
					Image: "docker.io/library/redis:7"
					Network: [
						units.networks.default.#self,
					]
				}
				Service: {
					Restart: "always"
				}
			}
			web: {
				Container: {
					Image:         "ghcr.io/paperless/paperless:2.14"
					ContainerName: "paperless"
					Environment: [
						"PAPERLESS_DBHOST=db",
					]
					EnvironmentFile: [
						"./app.env",
					]
					Network: [
						units.networks.default.#self,
					]
					PublishPort: [
						"8000:8000",
						"127.0.0.1:9000:9001/udp",
					]
					Volume: [
						units.volumes.data.#self & {target: "/usr/src/paperless/data"},
						"./export:/usr/src/paperless/export:ro",
					]
					Label: [
						"traefik.enable=true",
					]
				}
				Service: {
					Restart: "on-failure"
				}
				Unit: {
					After: [
						units.containers.db.#service,
						units.containers.redis_broker.#service,
					]
					Requires: [
						units.containers.db.#service,
						units.containers.redis_broker.#service,
					]
				}
			}
		}
	}
}

// ─── source: testdata/multi-stack/compose.yaml ───
// name: paperless
// services:
//   web:
//     image: ghcr.io/paperless/paperless:2.14
//     container_name: paperless
//     ports: ["8000:8000", "127.0.0.1:9000:9001/udp"]
//     environment:
//       PAPERLESS_DBHOST: db
//     env_file: [./app.env]
//     volumes:
//       - data:/usr/src/paperless/data
//       - ./export:/usr/src/paperless/export:ro
//     depends_on:
//       db: {condition: service_healthy}
//       redis-broker: {condition: service_started}
//     restart: unless-stopped
//     labels: {traefik.enable: "true"}
//   db:
//     image: docker.io/library/postgres:16
//     volumes: [pg-data:/var/lib/postgresql/data]
//     healthcheck:
//       test: ["CMD-SHELL", "pg_isready -U paperless"]
//       interval: 30s
//       timeout: 5s
//       retries: 5
//     restart: always
//   redis-broker:
//     image: docker.io/library/redis:7
//     restart: always
// volumes:
//   data:
//   pg-data:
