// Command gen-systemd-sections generates CUE schema for systemd's pass-through
// unit-file sections ([Unit]/[Service]/[Install]) from systemd's own parser
// table (load-fragment-gperf.gperf.in), so the schema tracks systemd rather
// than being hand-maintained.
//
// The table is the ground truth for which directives are valid on disk and in
// which section; the config_parse_* function for each gives its base type. Enum
// *values* aren't in this table (they live in systemd's DEFINE_STRING_TABLE_*
// lookups), so enum-typed directives map to a curated CUE type where we have one
// (e.g. #JobMode) and otherwise fall back to string with a TODO.
//
// Prototype: handles the [Unit] section (no macros). [Service] additionally
// needs the EXEC/CGROUP/KILL_CONTEXT macro expansion.
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
)

// cueType maps a config_parse_* function to a CUE type. Unmapped parsers fall
// back to string (safe). "" means "skip this directive" (deprecated/obsolete).
var cueType = map[string]string{
	// booleans
	"config_parse_bool":             "bool",
	"config_parse_tristate":         "bool",
	"config_parse_job_mode_isolate": "bool",
	// durations
	"config_parse_sec":                     "#TimeSpan",
	"config_parse_job_timeout_sec":         "#TimeSpan",
	"config_parse_job_running_timeout_sec": "#TimeSpan",
	// integers
	"config_parse_unsigned": "uint",
	// string lists (repeatable / space-separated)
	"config_parse_unit_deps":       "[...string]",
	"config_parse_documentation":   "[...string]",
	"config_parse_unit_mounts_for": "[...string]",
	// plain strings / paths
	"config_parse_unit_string_printf": "string",
	"config_parse_unit_path_printf":   "string",
	"config_parse_reboot_parameter":   "string",
	"config_parse_exit_status":        "string",
	// condition/assert families: repeatable, value is a string (path or expr)
	"config_parse_unit_condition_string": "[...string]",
	"config_parse_unit_condition_path":   "[...string]",
	// enums we already model
	"config_parse_job_mode": "#JobMode",
	// enums whose value tables aren't in the gperf (TODO: scrape *_table)
	"config_parse_emergency_action": "string", // TODO: #EmergencyAction
	"config_parse_collect_mode":     "string", // TODO: #CollectMode

	// skipped (deprecated / obsolete)
	"config_parse_warn_compat":        "",
	"config_parse_obsolete_unit_deps": "",
}

type directive struct {
	name, parser, cueType string
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gen-systemd-sections <gperf-file> <Section>")
		os.Exit(2)
	}
	gperfPath, section := os.Args[1], os.Args[2]

	f, err := os.Open(gperfPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	var dirs []directive
	seen := map[string]bool{}
	unmapped := map[string]bool{}
	prefix := section + "."
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if !strings.HasPrefix(line, prefix) {
			continue
		}
		fields := strings.Split(line, ",")
		if len(fields) < 2 {
			continue
		}
		name := strings.TrimSpace(strings.TrimPrefix(fields[0], prefix))
		parser := strings.TrimSpace(fields[1])
		if name == "" || seen[name] {
			continue
		}
		t, mapped := cueType[parser]
		if mapped && t == "" {
			continue // explicitly skipped (deprecated/obsolete)
		}
		if !mapped {
			t = "string" // safe fallback for unmapped parsers
			unmapped[parser] = true
		}
		seen[name] = true
		dirs = append(dirs, directive{name, parser, t})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// Group: core directives first (gperf order), then Condition*/Assert*.
	var core, conditions, asserts []directive
	for _, d := range dirs {
		switch {
		case strings.HasPrefix(d.name, "Condition"):
			conditions = append(conditions, d)
		case strings.HasPrefix(d.name, "Assert"):
			asserts = append(asserts, d)
		default:
			core = append(core, d)
		}
	}
	sort.Slice(conditions, func(i, j int) bool { return conditions[i].name < conditions[j].name })
	sort.Slice(asserts, func(i, j int) bool { return asserts[i].name < asserts[j].name })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/gen-systemd-sections; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: systemd load-fragment-gperf.gperf.in, [%s] section.\n", section)
	fmt.Fprintf(&b, "package creidhne\n\n")
	fmt.Fprintf(&b, "#%sSection: {\n", section)
	emit := func(title string, ds []directive) {
		if len(ds) == 0 {
			return
		}
		fmt.Fprintf(&b, "\t// %s\n", title)
		for _, d := range ds {
			fmt.Fprintf(&b, "\t%s?: %s\n", d.name, d.cueType)
		}
	}
	emit("core directives", core)
	emit("Condition* (systemd.unit(5))", conditions)
	emit("Assert* (systemd.unit(5))", asserts)
	fmt.Fprintf(&b, "}\n")

	fmt.Print(b.String())
	fmt.Fprintf(os.Stderr, "generated #%sSection: %d core, %d condition, %d assert (%d total)\n",
		section, len(core), len(conditions), len(asserts), len(core)+len(conditions)+len(asserts))
	if len(unmapped) > 0 {
		var names []string
		for p := range unmapped {
			names = append(names, p)
		}
		sort.Strings(names)
		fmt.Fprintf(os.Stderr, "NOTE: %d parser(s) fell back to string (add to cueType for richer types): %s\n",
			len(names), strings.Join(names, ", "))
	}
}
